spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/jobpilot
spring.datasource.username=jobpilot
spring.datasource.password=jobpilot
spring.jpa.hibernate.ddl-auto=update
